services:
  namesrv:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-namesrv
    command: sh mqnamesrv
    networks:
      - rocketmq
    ports:
      - "9876:9876"

  broker:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-broker
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/rocketmq-5.1.0/conf/broker.conf
    ports:
      - "10911:10911"
      - "10909:10909"
      - "10912:10912"
    depends_on:
      - namesrv
    networks:
      - rocketmq
    volumes:
      - D:/WorkingApp/rocketmq/broker/broker.conf:/home/rocketmq/rocketmq-5.1.0/conf/broker.conf
      - D:/WorkingApp/rocketmq/data:/home/rocketmq/store

  proxy:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-proxy
    networks:
      - rocketmq
    depends_on:
      - broker
      - namesrv
    ports:
      - "8081:8081"
      - "8080:8080"
    restart: on-failure
    environment:
      - NAMESRV_ADDR=namesrv:9876
    command: sh mqproxy

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-namesrv:9876
    ports:
      - "8082:8080"
    networks:
      - rocketmq
    depends_on:
      - namesrv
      - broker

networks:
  rocketmq:
    driver: bridge